// Master data - Hardcoded configurations
export const PUBLICATIONS = [
  { id: 1, name: "MNG UTHARA DESAM", code: "1502" },
  { id: 2, name: "SAMYUKTA KARNATAKA - MANGALORE", code: "1502" },
  { id: 3, name: "MADHYAMA BIMBA - MANGALORE", code: "1502" },
  { id: 4, name: "TULUNADU VARTHE - MANGALORE", code: "1502" },
  { id: 5, name: "VIVEKA SAMPADA - MANGALORE", code: "1502" },
  { id: 6, name: "MNG DIGANTHA MUDRANA", code: "1502" },
  { id: 7, name: "MNG MADHUBAN GRAPHICS", code: "1502" },
  { id: 8, name: "TIMES OF BEDRA", code: "1502" },
  { id: 9, name: "TULUNADA BOLPU", code: "1502" },
  { id: 10, name: "HBL JANAMADHYAMA", code: "1503" },
  { id: 11, name: "HBL SIRSI SAMACHAR", code: "1503" },
  { id: 12, name: "HBL TATVA NISHTA", code: "1503" },
  { id: 13, name: "THE NEWS TRAIL", code: "1503" },
  { id: 14, name: "RAJYADHARMA - MYSORE", code: "1505" },
  { id: 15, name: "HELLO MYSORE - MYSORE", code: "1505" },
  { id: 16, name: "PRATHINIDHI - MYSORE", code: "1505" },
  { id: 17, name: "MYS KANNADIGARA PRAJANUDI", code: "1505" },
  { id: 18, name: "MYS VISHWADHUTHA", code: "1505" },
  { id: 19, name: "MYS MYSORE VIJAYA", code: "1505" },
  { id: 20, name: "SAMYUKTHA KARNATAKA - BAGALKOT", code: "1506" },
  { id: 21, name: "GVT HAMPI TIMES", code: "1507" },
  { id: 22, name: "GVT LOKA DWANI", code: "1507" },
  { id: 23, name: "ECHHARIKE - SHIMOGA", code: "1508" },
  { id: 24, name: "KRANTHI DEEPA - SHIMOGA", code: "1508" },
  { id: 25, name: "JANA HORATA - SHIMOGA", code: "1508" },
  { id: 26, name: "JAI KARUNADU KALA - SHIMOGA", code: "1508" },
  { id: 27, name: "KANNADA PRABHA - SHIMOGA", code: "1508" },
  { id: 28, name: "SMG MALENADU MITRA", code: "1508" },
  { id: 29, name: "SHIVAMOGGA TIMES - SHIMOGA", code: "1508" },
  { id: 30, name: "SAMYUKTA KARNATAKA - GULBARGA", code: "1509" },
  { id: 31, name: "GLB MALLAMMANA NUDI", code: "1509" },
  { id: 32, name: "NISARGA SARATHYA DAILY NEWS - GLB", code: "1509" },
  { id: 33, name: "GLB SALAR DAILY", code: "1509" },
  { id: 34, name: "VAARTHA BHARATHI", code: "1509" },
  { id: 35, name: "SAMYUKTA KARNATAKA - BELAGAVI", code: "1511" },
  { id: 36, name: "Bengaluru Rural", code: "1501" },
  { id: 37, name: "Bengaluru city", code: "1501" },
  { id: 38, name: "VK student Edition", code: "1501" },
  { id: 39, name: "Lavala VK", code: "1501" },
  { id: 40, name: "BLG VKMINI SPLIT", code: "1501" },
  { id: 41, name: "Karwara", code: "1501" },
  { id: 42, name: "Belagavi Main", code: "1501" },
  { id: 43, name: "BLG VKMINI SPLIT", code: "1501" },
  { id: 44, name: "BELGAVI VKMINI", code: "1501" },
  { id: 45, name: "Namma Chikkodi", code: "1501" },
  { id: 46, name: "Namma Belagavi", code: "1501" },
  { id: 47, name: "Namma BailaHongala", code: "1501" },
  { id: 48, name: "Namma Haveri", code: "1501" },
  { id: 49, name: "Namma Karawara", code: "1501" },
  { id: 50, name: "Namma Gadag", code: "1501" },
  { id: 51, name: "Namma Mahanagara", code: "1501" },
  { id: 52, name: "Hubballi", code: "1501" },
  { id: 53, name: "HBL VKMINI SPLIT", code: "1501" },
  { id: 54, name: "HUBLI VKMINI", code: "1501" },
  { id: 55, name: "Vk Main", code: "1501" },
  { id: 56, name: "Namma Kasargod", code: "1501" },
  { id: 57, name: "Namma Puttur", code: "1501" },
  { id: 58, name: "Namma Mangalore", code: "1501" },
  { id: 59, name: "Namma Udupi", code: "1501" },
  { id: 60, name: "Vkmnc", code: "1501" },
  { id: 61, name: "MANGALORE VKMINI", code: "1501" },
  { id: 62, name: "MNG VKMINI SPLIT", code: "1501" },
  { id: 63, name: "Namma Bantwala", code: "1501" },
  { id: 64, name: "Namma Kundapur", code: "1501" },
  { id: 65, name: "MYSORE", code: "1501" },
  { id: 66, name: "Hassan", code: "1501" },
  { id: 67, name: "MYSORE VKMINI", code: "1501" },
  { id: 68, name: "MYSSPL", code: "1501" },
  { id: 69, name: "VKGAN", code: "1501" },
  { id: 70, name: "Namma Vijayanagara", code: "1501" },
  { id: 71, name: "Namma Raichur", code: "1501" },
  { id: 72, name: "Namma Bellary", code: "1501" },
  { id: 73, name: "VK CTDMAIN", code: "1501" },
  { id: 74, name: "Namma Chitradurga", code: "1501" },
  { id: 75, name: "CTD VKMINI SPLIT", code: "1501" },
];

export const MACHINES = [
  { id: 1, name: "City Line", code: "CL" },
  { id: 2, name: "High Line", code: "HL" },
  { id: 3, name: "Eco Line", code: "EL" },
  { id: 4, name: "News line s30", code: "NL" },
];

export const DOWNTIME_REASONS = [
  { id: 1, reasons: "Mechanical down time", code: "MDT" },
  { id: 2, reasons: "Electrical", code: "EDT" },
  { id: 3, reasons: "Ink Issues", code: "IK" },
  { id: 4, reasons: "Web brake", code: "WB" },
  { id: 5, reasons: "Reel change", code: "RC" },
  { id: 6, reasons: "Cleaning", code: "CL" },
];

export const NEWSPRINT_TYPES = [
  { id: 1, name: "Ramdas", code: "RMD" },
  { id: 2, name: "Shree Lakshmi Tulasi", code: "SLT" },
  { id: 3, name: "Imported", code: "IMP" },
];

export const USERS = [
  {
    id: 1,
    email: "alvin.pinto@timosofindia.com",
    name: "Alwin Pinto",
    password: "Mmcl@1502",
    phone_number: "9964023020",
    location: "Mangalore",
    location_code: "MNG1502",
    role: "user",
  },
  {
    id: 2,
    email: "sanjay.k@timesofindia.com",
    name: "Sanjay Kanekal",
    password: "Mmcl@1503",
    phone_number: "9341111918",
    location: "Hubli",
    location_code: "HBL1503",
    role: "user",
  },
  {
    id: 3,
    email: "shivaprasad.n@timesofindia.com",
    name: "Shivprasad",
    password: "Mmcl@1505",
    phone_number: "9876543212",
    location: "Mysore",
    location_code: "MYS1505",
    role: "user",
  },
  {
    id: 4,
    email: "gururaj.r@timesofindia.com",
    name: "Gururaj R",
    password: "Mmcl@1506",
    phone_number: "9483905222",
    location: "Bagalkote",
    location_code: "BKT1506",
    role: "user",
  },
  {
    id: 5,
    email: "hiremath.s@timeofindia.com",
    name: "Shiv Kumar hiremath",
    password: "Mmcl@1507",
    phone_number: "9341110974",
    location: "Gangavati",
    location_code: "GVT1507",
    role: "user",
  },
  {
    id: 6,
    email: "narappa.gowdru@timesofindia.com",
    name: "Narappa GP",
    password: "Mmcl@1508",
    phone_number: "9845238195",
    location: "Shimoga",
    location_code: "SMG1508",
    role: "user",
  },
  {
    id: 7,
    email: "raghavendraorao.inamdar@timesofindia.com",
    name: "Raghavendra",
    password: "Mmcl@1509",
    phone_number: "9341110885",
    location: "Gulbarga",
    location_code: "GLB1509",
    role: "user",
  },
  {
    id: 8,
    email: "shiddappa.kashibadiger@timesofindia.com",
    name: "Shiddappa",
    password: "Mmcl@1511",
    phone_number: "9739996689",
    location: "Belgaum",
    location_code: "BGM1511",
    role: "user",
  },
  {
    id: 9,
    email: "user@gmail.com",
    name: "Generic User",
    password: "user@123",
    phone_number: "9000000000",
    location: "Generic Location",
    location_code: "GL0001",
    role: "user",
  },
  {
    id: 10,
    email: "vinay.gh@timesofindia.com",
    name: "Vinay",
    password: "Mmcl@1501",
    phone_number: "9739948515",
    location: "Bengaluru",
    location_code: "BNG1501",
    role: "user",
  },
];

export const ADMINS = [
  {
    id: 11,
    email: "deepak.saluja@timesofindia.com",
    name: "Deepak Saluja",
    password: "Admin@123",
    phone_number: "9999999991",
    location: "Bangalore",
    location_code: "BNG001",
    role: "admin",
  },
  {
    id: 12,
    email: "girish.k@timesofindia.com",
    name: "Girish Bhat",
    password: "Admin@123",
    phone_number: "9999999992",
    location: "Bangalore",
    location_code: "HO001",
    role: "admin",
  },
  {
    id: 13,
    email: "lokesh.vgowda@timesofindia.com",
    name: "Lokesh",
    password: "admin123",
    phone_number: "9999999993",
    location: "Bangalore",
    location_code: "CORP001",
    role: "admin",
  },
];

export const ALL_USERS = [...USERS, ...ADMINS];

// Helper to get all unique locations from users
export const LOCATIONS = Array.from(
  new Set(ALL_USERS.map((u) => u.location)),
).sort();
